---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ role_path }}/vars/aep.csv"
    fieldnames: aep,desc,infra_vlan,state
    delimiter: ","
  register: aep
- name: Add AEP
  cisco.aci.aci_aep:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    aep: "{{ item.aep }}"
    description: "{{ item.desc }}"
    infra_vlan: "{{ item.infra_vlan }}"
    state: "{{ item.state }}"
  loop: "{{ aep.list[1:] }}"
