---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/app_profile.csv"
    fieldnames: tenant,ap,mon_pol,desc
    delimiter: ","
  register: app_profile
- name: Configure Application Profile
  cisco.aci.aci_ap:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    monitoring_policy: "{{ item.mon_pol }}"
    description: "{{ item.desc }}"
    state: "{{ state }}"
  loop: "{{ app_profile.list[1:] }}"
