---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ role_path }}/vars/bd.csv"
    fieldnames: tenant,bd,vrf,arp_flooding,l2_unknown_unicast,limit_ip_learn,state
    delimiter: ","
  register: bd
- name: Add Bridge Domain
  cisco.aci.aci_bd:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    bd: "{{ item.bd }}"
    vrf: "{{ item.vrf }}"
    arp_flooding: "{{ item.arp_flooding }}"
    l2_unknown_unicast: "{{ item.l2_unknown_unicast }}"
    limit_ip_learn: "{{ item.limit_ip_learn }}"
    state: "{{ item.state }}"
  loop: "{{ bd.list[1:] }}"
