---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/cdp.csv"
    fieldnames: name,adm_state
    delimiter: ","
  register: cdp
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/lldp.csv"
    fieldnames: lldp_policy,rx_state,tx_state
    delimiter: ","
  register: lldp
- name: Configure CDP policies
  cisco.aci.aci_interface_policy_cdp:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    name: "{{ item.name }}"
    admin_state: "{{ item.adm_state }}"
    state: "{{ state }}"
  loop: "{{ cdp.list[1:] }}"
  when: item.name != ""
- name: Configure LLDP policies
  cisco.aci.aci_interface_policy_lldp:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    lldp_policy: "{{ item.lldp_policy }}"
    receive_state: "{{ item.rx_state }}"
    transmit_state: "{{ item.tx_state }}"
    state: "{{ state }}"
  loop: "{{ lldp.list[1:] }}"
  when: item.lldp_policy != ""
