---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ role_path }}/vars/contract.csv"
    fieldnames: tenant,contract,scope,subject,apply_both_direction,reverse_filter,action,filter,entry,ether_type,ip_protocol,dst_port_start,dst_port_end,cont_desc,subj_desc,filt_desc,state
    delimiter: ","
  register: contract
- name: Add Filter
  vars:
    unique_filter: "{{ contract.list[1:] | unique('tenant','filter','filt_desc','state') }}"
  cisco.aci.aci_filter:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    filter: "{{ item.filter }}"
    description: "{{ item.filt_desc }}"
    tenant: "{{ item.tenant }}"
    state: "{{ item.state }}"
  loop: "{{ unique_filter }}"
  when: item.filter != ""
- name: Add Filter Entries
  vars:
     unique_filentry: "{{ contract.list[1:] | unique('tenant','filter','entry','ether_type','ip_protocol','dst_port_start','dst_port_end','state') }}"
  cisco.aci.aci_filter_entry:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    entry: "{{ item.entry }}"
    filter: "{{ item.filter }}"
    tenant: "{{ item.tenant }}"
    ether_type: "{{ item.ether_type }}"
    ip_protocol: "{{ item.ip_protocol }}"
    dst_port_start: "{{ item.dst_port_start }}"
    dst_port_end: "{{ item.dst_port_end }}"
    state: "{{ item.state }}"
  loop: "{{ unique_filentry }}"
  when: item.entry != ""
- name: Add Contract
  vars:
    unique_contract: "{{ contract.list[1:] | unique('tenant','contract','scope','cont_desc','state') }}"
  cisco.aci.aci_contract:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    contract: "{{ item.contract }}"
    description: "{{ item.cont_desc }}"
    scope: "{{ item.scope }}"
    state: "{{ item.state }}"
  loop: "{{ unique_contract }}"
- name: Add Contract Subject
  vars:
    unique_contsub: "{{ contract.list[1:] | unique('tenant','contract','subject','subj_desc','reverse_filter','apply_both_direction','state') }}"
  cisco.aci.aci_contract_subject:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    contract: "{{ item.contract }}"
    subject: "{{ item.subject }}"
    description: "{{ item.subj_desc }}"
    reverse_filter: "{{ item.reverse_filter }}"
    apply_both_direction: "{{ item.apply_both_direction }}"
    state: "{{ item.state }}"
  loop: "{{ unique_contsub }}"
  when: item.subject != ""
- name: Bind Contract Subject with Filter
  vars:
    unique_contract: "{{ contract.list[1:] | unique('tenant','contract','subject','filter','action','state') }}"
  cisco.aci.aci_contract_subject_to_filter:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    contract: "{{ item.contract }}"
    subject: "{{ item.subject }}"
    filter: "{{ item.filter }}"
    action: "{{ item.action }}"
    state: "{{ item.state }}"
  loop: "{{ unique_contract }}"
  when: item.contract != "" and item.subject != "" and item.filter != ""
