---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/domain.csv"
    fieldnames: domain,domain_type,vm_provider,state
    delimiter: ","
  register: domain
- name: Add domain without vmm
  cisco.aci.aci_domain:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    state: "{{ item.state }}"
  loop: "{{ domain.list[1:] }}"
  when: item.vm_provider == ""
- name: Add domain with vmm
  cisco.aci.aci_domain:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    vm_provider: "{{ item.vm_provider }}"
    state: "{{ item.state }}"
  loop: "{{ domain.list[1:] }}"
  when: item.vm_provider
