---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ role_path }}/vars/epg.csv"
    fieldnames: tenant,ap,epg,bd,desc,domain,dom_type,contract,cont_type,state
    delimiter: ","
  register: epg
- name: Add EPG
  cisco.aci.aci_epg:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.epg }}"
    description: "{{ item.desc }}"
    bd: "{{ item.bd }}"
    state: "{{ item.state }}"
  loop: "{{ epg.list[1:] }}"
- name: Bind EPG to Domain
  cisco.aci.aci_epg_to_domain:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.epg }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.dom_type }}"
    state: "{{ item.state }}"
  loop: "{{ epg.list[1:] }}"
  when: item.domain != ""
- name: Bind EPG to Contract
  cisco.aci.aci_epg_to_contract:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.epg }}"
    contract: "{{ item.contract }}"
    contract_type: "{{ item.cont_type }}"
    state: "{{ item.state }}"
  loop: "{{ epg.list[1:] }}"
  when: item.contract != ""
