---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/l3out_vpc.csv"
    fieldnames: tenant,l3out_name,node_profile,int_profile,pod_id,node_id,path_ep,side,address,secondary_address,state
    delimiter: ","
  register: l3out_int
- name: Add L3out VPC SVI IP Address
  cisco.aci.aci_l3out_logical_interface_vpc_member:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    l3out: "{{ item.l3out_name }}"
    node_profile: "{{ item.node_profile }}"
    interface_profile: "{{ item.int_profile }}"
    pod_id: "{{ item.pod_id }}"
    node_id: "{{ item.node_id }}"
    path_ep: "{{ item.path_ep }}"
    side: "{{ item.side }}"
    address: "{{ item.address }}"
    state: "{{ item.state }}"
  loop: "{{ l3out_int.list[1:] }}"
- name: Add L3out VPC SVI Secondary IP Address
  vars: 
    vpc_2nd_address: "{{ l3out_int.list[1:] | unique('tenant','l3out_name','node_profile','int_profile','pod_id','node_id','path_ep','side','secondary_address','state') }}"
  cisco.aci.aci_l3out_interface_secondary_ip:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    l3out: "{{ item.l3out_name }}"
    node_profile: "{{ item.node_profile }}"
    interface_profile: "{{ item.int_profile }}"
    pod_id: "{{ item.pod_id }}"
    node_id: "{{ item.node_id }}"
    path_ep: "{{ item.path_ep }}"
    side: "{{ item.side }}"
    address: "{{ item.secondary_address }}"
    state: "{{ item.state }}"
  loop: "{{ vpc_2nd_address }}"
