---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/l3out.csv"
    fieldnames: tenant,l3out_name,l3out_desc,dom,vrf,route_control,protocol,ospf_type,ospf_area,api_rest_method
    delimiter: ","
  register: l3out
- name: Configure L3out for OSPF only
  vars:
    unique_l3out: "{{ l3out.list[1:] | unique('tenant','l3out_name','l3out_desc','dom','vrf','route_control','protocol') }}"
  cisco.aci.aci_l3out:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    name: "{{ item.l3out_name }}"
    description: "{{ item.l3out_desc }}"
    domain: "{{ item.dom }}"
    vrf: "{{ item.vrf }}"
    route_control: "{{ item.route_control }}"
    l3protocol: "{{ item.protocol }}"
    state: "{{ state }}"
  loop: "{{ unique_l3out }}"
- name: Update L3out OSPF Configuration
  vars:
    ospf_update: "{{ l3out.list[1:] | unique('tenant','l3out_name','ospf_type','ospf_area','api_rest_method') }}"
  cisco.aci.aci_rest:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    method: "{{ item.api_rest_method }}"
    path: /api/node/mo/uni/tn-{{ item.tenant }}/out-{{ item.l3out_name }}.json
    content:
       {
         "l3extOut": {
           "attributes": {
             "dn": "uni/tn-Heroes_Evils/out-{{ item.l3out_name }}",
           },
           "children": [
             {
               "ospfExtP": {
                 "attributes": {
                   "areaCost": "1",
                   "areaCtrl": "redistribute,summary",
                   "areaId": "{{ item.ospf_area }}",
                   "areaType": "{{ item.ospf_type }}",
                 }
               }
             }
           ]
         }
       }
  loop: "{{ ospf_update }}"
