---
# tasks file for aci
# old using static task (import_tasks), update it using dynamic task (import_tasks)
# include_tasks not working with tags, it only load it
# order matter since aci some of aci configuration depent on other configuration

# Access Policied Definition
- name: Configure Link Level
  import_tasks: link_level.yml
  tags:
    - link_level
    - access_policies
    - never

- name: Configure CDP & LLDP 
  import_tasks: cdp_lldp.yml
  tags:
    - cdp_lldp
    - access_policies
    - never

- name: Configure Port-Channel 
  import_tasks: port_channel.yml
  tags:
    - port_channel
    - access_policies
    - never

- name: Configure VPC Domain
  import_tasks: vpc_domain.yml
  tags:
    - vpc_domain
    - access_policies
    - never

- name: Configure policy Group
  import_tasks: polgroup.yml
  tags: 
    - polgroup
    - access_policies
    - never

- name: Configure Interface Profile
  import_tasks: intprof.yml
  tags:
    - intprof
    - access_policies
    - never

- name: Configure Interface Selector
  import_tasks: intsel.yml
  tags:
    - intsel
    - access_policies
    - never

- name: Configure Switch Profile
  import_tasks: switchprof.yml
  tags:
    - switchprof
    - access_policies
    - never

- name: Update Switch Profile
  import_tasks: update_switchprof.yml
  tags:
    - update_switchprof
    - access_policies
    - never

- name: Configure Vlan Pool
  import_tasks: vlanpool.yml
  tags:
    - vlanpool
    - access_policies
    - never

- name: Update Vlan Pool Range
  import_tasks: update_vlanpoolrange.yml
  tags:
    - update_vlanpoolrange
    - access_policies
    - never

- name: Configure AEP
  import_tasks: aep.yml
  tags:
    - aep
    - access_policies
    - never

- name: Configure Domain
  import_tasks: domain.yml
  tags:
    - domain
    - access_policies
    - never

- name: Update Domain Bind to Vlan Pool
  import_tasks: update_domain_vlanpool.yml
  tags:
    - update_domain_vlanpool
    - access_policies
    - never

- name: Update Domain Bind to AEP
  import_tasks: update_domain_aep.yml
  tags:
    - update_domain_aep
    - access_policies
    - never

# Tenant Policies Definition
- name: Create Tenant
  import_tasks: tenant.yml
  tags:
    - tenant
    - tenant_policies
    - never

- name: Create App Profile
  import_tasks: app_profile.yml
  tags:
    - app_profile
    - tenant_policies
    - never

- name: Create VRF
  import_tasks: vrf.yml
  tags:
    - vrf
    - tenant_policies
    - never

- name: Create L3out
  import_tasks: l3out.yml
  tags:
    - l3out
    - tenant_policies
    - never

- name: Create L3out Node
  import_tasks: l3out_node.yml
  tags:
    - l3out
    - l3out_node
    - tenant_policies
    - never

- name: Create L3out Interface
  import_tasks: l3out_interface.yml
  tags:
    - l3out
    - l3out_interface
    - tenant_policies
    - never

- name: Create L3out SVI IP Configureress 
  import_tasks: l3out_vpc.yml
  tags:
    - l3out
    - l3out_vpc
    - tenant_policies
    - never

- name: Create L3out EPG
  import_tasks: l3out_extepg.yml
  tags:
    - l3out
    - l3out_epg
    - tenant_policies
    - never

- name: Create Contract
  import_tasks: contract.yml
  tags:
    - contract
    - tenant_policies
    - never

- name: Create Bridge Domain
  import_tasks: bd.yml
  tags:
    - bd
    - tenant_policies
    - never

- name: Create EPG
  import_tasks: epg.yml
  tags:
    - epg
    - tenant_policies
    - never

- name: Update EPG static port
  import_tasks: epg_staticport.yml
  tags:
    - epg_staticport
    - tenant_policies
    - never

- name: Apply vzAny
  import_tasks: vzany.yml
  tags:
    - vzany
    - tenant_policies
    - never

# Ulitilies Definition
- name: Help
  ansible.builtin.debug:
    msg:
    - "ansible-playbook aci.yml --list-tags -> check available tags"
    - "ansible-playbook aci.yml --tags tags-1,tags-2,tags-n --ask-vault-pass -> will run tagged task"
  tags: help
