---
# tasks file for aci
# old using static task (import_tasks), update it using dynamic task (import_tasks)
# include_tasks not working with tags, it only load it
# order matter since aci some of aci configuration depent on other configuration

# Access Policied Definition
- name: Add VPC Domain
  import_tasks: vpc_domain.yml
  tags:
    - vpc_domain
    - access_policies
    - never

- name: Add policy Group
  import_tasks: polgroup.yml
  tags: 
    - polgroup
    - access_policies
    - never

- name: Add Interface Profile
  import_tasks: intprof.yml
  tags:
    - intprof
    - access_policies
    - never

- name: Add Interface Selector
  import_tasks: intsel.yml
  tags:
    - intsel
    - access_policies
    - never

- name: Add Switch Profile
  import_tasks: switchprof.yml
  tags:
    - switchprof
    - access_policies
    - never

- name: Update Switch Profile
  import_tasks: update_switchprof.yml
  tags:
    - update_switchprof
    - access_policies
    - never

- name: Add Vlan Pool
  import_tasks: vlanpool.yml
  tags:
    - vlanpool
    - access_policies
    - never

- name: Update Vlan Pool Range
  import_tasks: update_vlanpoolrange.yml
  tags:
    - update_vlanpoolrange
    - access_policies
    - never

- name: Update Domain Bind to Vlan Pool
  import_tasks: update_domain_vlanpool.yml
  tags:
    - update_domain_vlanpool
    - access_policies
    - never

# Tenant Policies Definition
- name: Create Contract
  import_tasks: contract.yml
  tags:
    - contract
    - tenant_policies
    - never

# Ulitilies Definition
- name: Help
  ansible.builtin.debug:
    msg:
    - "ansible-playbook aci.yml --list-tags -> check available tags"
    - "ansible-playbook aci.yml --tags tags-1,tags-2,tags-n --ask-vault-pass -> will run tagged task"
  tags: help
