---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/update_domain_vlanpool.csv"
    fieldnames: domain,domain_type,pool,pool_allocation_mode,vm_provider
    delimiter: ","
  register: domain
- name: Update Domain to Vlan Pool Mapping
  cisco.aci.aci_domain_to_vlan_pool:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    pool: "{{ item.pool }}"
    pool_allocation_mode: "{{ item.pool_allocation_mode }}"
    state: "{{ state }}"
  loop: "{{ domain.list[1:] }}"
  when: item.vm_provider == ""
- name: Update VMM Domain to Vlan Pool Mapping
  cisco.aci.aci_domain_to_vlan_pool:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    pool: "{{ item.pool }}"
    pool_allocation_mode: "{{ item.pool_allocation_mode }}"
    vm_provider: "{{ item.vm_provider }}"
    state: "{{ state }}"
  loop: "{{ domain.list[1:] }}"
  when: item.vm_provider
