---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/vpc_domain.csv"
    fieldnames: name,id,sw_1,sw_2
    delimiter: ","
  register: vpc_domain
- name: Configure VPC domain
  cisco.aci.aci_switch_policy_vpc_protection_group:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    protection_group: "{{ item.name }}"
    protection_group_id: "{{ item.id }}"
    switch_1_id: "{{ item.sw_1 }}"
    switch_2_id: "{{ item.sw_2 }}"
    state: "{{ state }}"
  loop: "{{ vpc_domain.list[1:] }}"
