---
- name: Read CSV File
  community.general.read_csv:
    path: "{{ playbook_dir }}/vars/vzany.csv"
    fieldnames: tenant,vrf,contract,type
    delimiter: ","
  register: vzany
- name: Apply vzany 
  cisco.aci.aci_vzany_to_contract:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    tenant: "{{ item.tenant }}"
    vrf: "{{ item.vrf }}"
    contract: "{{ item.contract }}"
    type: "{{ item.type }}"
    state: "{{ state }}"
  loop: "{{ vzany.list[1:] }}"
